mate-desktop/mate-screensaver

src/gs-manager.c
Fading to black has negative security consequences: the screen locking
and actual suspend race with each other, and this can result in the
screen's contents being briefly visible after resume.
This has been reported as #54 but has been known and patched for in
Debian/Ubuntu since at least 2010 (see LP 546578).
=> Don't fade to black when locking the screen

src/gs-grab-x11.c
fixes https://github.com/mate-desktop/mate-screensaver/issues/104
Issue was caused by https://github.com/mate-desktop/mate-screensaver/commit/051d9df1ca81e586f43d1d95a1ac3159452d4f17
@XRevan86 
Please test and review
=> GTK+-3 gs-grab-x11: use correct GTK_VERSION_CHECK

src/gs-lock-plug.c
In some systems the gdm binary is actually called "gdm-binary", so we
need to check for that too.
=> Also look for gdm-binary process

data/mate-screensaver-preferences.ui, savers/floaters.c, savers/gs-theme-engine.c, src/gs-fade.c, src/gs-grab-x11.c, src/gs-grab.h, src/gs-job.c, src/gs-manager.c, src/gs-visual-gl.c, src/gs-visual-gl.h, src/gs-window-x11.c, src/gs-window.h, src/mate-screensaver-gl-helper.c, src/mate-screensaver-preferences.c, src/test-window.c
GTK+ 3.22 has broken them completely, and in mate-screensaver there aren't really a need in them at all, in any GTK+ version.
This fixes #98 and #103.
=> Avoid deprecated gdk_window_set_background functions

data/mate-screensaver-preferences.ui, savers/floaters.c, savers/gs-theme-engine.c, src/gs-manager.c, src/gs-window-x11.c, src/gs-window.h, src/mate-screensaver-preferences.c
GTK+ 3.22 has broken them completely, and in mate-screensaver there aren't really a need in them at all, in any GTK+ version.
Additionally this significantly reduces the gap between the code for GTK+2 and GTK+3.
=> 1.16: Avoid deprecated gdk_window_set_background functions

src/gs-window-x11.c
Hi, I found a bug in `shake_dialog` function.
When the password is wrong, the dialog will shake several times to indicate that result. However, there is a bug in `shake_dialog` function.
Variable `i` will increase from `0` to `8` and this `for loop` will be executed **odd times**, so the dialog will stay on the right of its original position.
I have changed the max value of `i` to `8` and it works properly!
=> Change shake times to even number, so the dialog can return to its original position.

src/copy-theme-dialog.c
I don't know how to trigger this GUI to see it, but i used replacements for GTK_FILL and GTK_EXPAND table options.
So this might be fine.
=> copy-theme-dialog: port GtkTable to GtkGrid

src/gs-grab-x11.c, src/gs-grab.h, src/gs-manager.c, src/gs-monitor.c, src/test-window.c
```gdk_keyboard_grab``` and ```gdk_pointer_grab``` are removed from GTK+ 4 making this an important change for the future.
Yet at the same time I can't be 100% confident because I'm touching (a lot) a very important part of screenlocking potentionally creating a "security issue".
=> Switch to GdkSeat for GTK+ 3.20 and newer

src/gs-window-x11.c
This fixes a regression introduced in commit 5d4416aa5853de486e62ca97207ee1da4b35b199 which causes screensaver windows to be displayed incorrectly in multi-monitor configurations where monitor geometries overlap (especially for mirrored monitor geometries, window geometries are calculated to zero).
=> Bug fix: screensaver and lock screen not correctly displayed in configurations with overlapping monitor geometries

configure.ac, src/Makefile.am, src/gs-auth-bsdauth.c, src/gs-auth-pwent.c, src/setuid.c
OpenBSD does not have nor use pam(8) for password authentication but
instead uses bsd_auth(3): add a bsd_auth authentication scheme to
make locking possible.
This has been a part of gnome-screensaver already but was probably
removed at one point. This is mostly identical to that code, with some
minor modifications.
=> Implement OpenBSD authentication using bsd_auth(3).

src/mate-screensaver-preferences.c
I began the work in https://github.com/mate-desktop/mate-screensaver/pull/138 but some languages didn't work
This is the fix to work in all languages
It works here with:
```
am_ET.UTF-8... done
ar_IQ.UTF-8... done
ar_SA.UTF-8... done
as_IN.UTF-8... done
ast_ES.UTF-8... done
be_BY.UTF-8... done
bg_BG.UTF-8... done
bn_BD.UTF-8... done
bn_IN.UTF-8... done
br_FR.UTF-8... done
bs_BA.UTF-8... done
ca_ES.UTF-8... done
ca_ES.UTF-8@valencia... done
cmn_TW.UTF-8... done
crh_UA.UTF-8... done
cs_CZ.UTF-8... done
cy_GB.UTF-8... done
da_DK.UTF-8... done
de_DE.UTF-8... done
dz_BT.UTF-8... done
el_GR.UTF-8... done
en_AU.UTF-8... done
en_CA.UTF-8... done
en_GB.UTF-8... done
es_AR.UTF-8... done
es_CO.UTF-8... done
es_ES.UTF-8... done
et_EE.UTF-8... done
eu_ES.UTF-8... done
fa_IR.UTF-8... done …
```
=>  Fix: idle slider display in all languages

src/gs-lock-plug.c
This fixes an issue where the lock screen widgets look wrong on GTK+ >= 3.23
=> lock-plug: Only scale lock-screen widgets on older versions of GTK

src/gs-manager.c, src/gs-window-x11.c
Print monitor in right place:
https://github.com/mate-desktop/mate-screensaver/blob/ef8f73d6f81ac3d841bf136960adf523204412ea/src/gs-manager.c#L1542-L1543
Please review and test:) @sc0w @raveit65
=> gs-manager.c: add missing debug information

src/gs-manager.c, src/gs-window-x11.c, src/gs-window.h, src/test-window.c
Finally this burden has been released from my shoulders :-).
=> Fix-up 5d4416a to solve lock by-passing

src/gs-fade.c
commit https://github.com/mate-desktop/mate-screensaver/commit/599bc81
changed the fade time out to be less than a 1000ms.  Unfortunately, this broke the fade because the
math for computing the number of fade steps used integer arithmetic,
and performed a division by a 1000.
https://bugzilla.gnome.org/show_bug.cgi?id=672583
origin commit:
https://gitlab.gnome.org/GNOME/gnome-screensaver/commit/7e2085a
=> fade: fix fade computation math

configure.ac, src/Makefile.am
Reuses WITH_SYSTEMD #define to reduce #ifdef mess.
ELOGIND is not officially supported, but since it's
a subset of systemd, it should work out of the box.
Co-authored-by: Joakim Tjernlund <joakim.tjernlund@infinera.com>
Fixes #187
=> Add ELOGIND support

configure.ac, src/gs-lock-plug.c, src/mate-screensaver-preferences.c
`find . -regextype posix-extended -regex '.*\.(c|h|ac)' -exec sed --in-place 's/[[:space:]]\+$//' {} \+`
like rbuj do on [https://github.com/mate-desktop/mate-control-center/pull/463](https://github.com/mate-desktop/mate-control-center/pull/463).
=> Remove trailing whitespaces

configure.ac, src/gs-grab-x11.c
The X server hasn't implemented it in over 10 years.
and it was dropped from debian since a long time.
fixes https://github.com/mate-desktop/mate-screensaver/issues/199
=> drop libXxf86 dependency

src/gs-lock-plug.c
```C
gtk_style_context_add_provider_for_screen (gdk_screen_get_default(),
GTK_STYLE_PROVIDER (style_provider),
GTK_STYLE_PROVIDER_PRIORITY_USER);
```
https://developer.gnome.org/gtk3/stable/GtkStyleContext.html#gtk-style-context-add-provider-for-screen
css data is located at /usr/share/mate-screensaver/lock-dialog-THEME.css, XDG_CONFIG_HOME/gtk-3.0/gtk.css, /usr/share/themes/...
/usr/share/mate-screensaver/lock-dialog-THEME.css file has highest priority, if exists:
```
$ gsettings get org.mate.screensaver lock-dialog-theme
'test'
$ grep lock-dialog /usr/share/mate-screensaver/lock-dialog-test.css
.lock-dialog.background {
.lock-dialog frame {
.lock-dialog notebook {
.lock-dialog entry,
.lock-dialog entry:focus {
.lock-dialog button,
.lock-dialog button:focus {
.lock-dialog button:hover, …
```
=> lock-dialog: add style_provider to current screen globally

src/gs-listener-dbus.c, src/gs-listener-dbus.h, src/gs-monitor.c
This patch fixes two issues #145 and #175. 
It is adopted from xfce4-screensaver patch:
https://git.xfce.org/apps/xfce4-screensaver/commit/?id=9e53bb2866
Introduced new Inhibitor lock to make sure lock was in place and
user will be greeted with unlock dialog when resumes from suspend/
hibernate.
=> Implement lock on suspend

savers/gste-popsquares.c, savers/gste-slideshow.c, src/copy-theme-dialog.c, src/gs-fade.c, src/gs-grab-x11.c, src/gs-job.c, src/gs-listener-dbus.c, src/gs-manager.c, src/gs-monitor.c, src/gs-prefs.c, src/gs-theme-manager.c, src/gs-watcher-x11.c, src/gs-window-x11.c, src/mate-screensaver-preferences.c
Fixes the warnings:
```
gs-monitor.c:62:40: warning: redundant redeclaration of 'gs_monitor_init' [-Wredundant-decls]
gs-monitor.c:62:40: warning: redundant redeclaration of 'gs_monitor_class_init' [-Wredundant-decls]
gs-watcher-x11.c:79:40: warning: redundant redeclaration of 'gs_watcher_init' [-Wredundant-decls]
gs-watcher-x11.c:79:40: warning: redundant redeclaration of 'gs_watcher_class_init' [-Wredundant-decls]
gs-listener-dbus.c:151:41: warning: redundant redeclaration of 'gs_listener_init' [-Wredundant-decls]
gs-listener-dbus.c:151:41: warning: redundant redeclaration of 'gs_listener_class_init' [-Wredundant-decls]
gs-manager.c:121:40: warning: redundant redeclaration of 'gs_manager_init' [-Wredundant-decls]
gs-manager.c:121:40: warning: redundant redeclaration of …
```
=> avoid redundant redeclarations

savers/floaters.c
```
floaters.c: In function ‘screen_saver_floater_should_come_on_screen’:
floaters.c:420:7: warning: using integer absolute value function ‘abs’ when argument is of floating-point type ‘double’ [-Wabsolute-value]
420 |  if ((abs (performance_ratio - .5) >= G_MINDOUBLE) &&
|       ^~~
floaters.c: In function ‘screen_saver_floater_create_path’:
floaters.c:585:6: warning: using integer absolute value function ‘abs’ when argument is of floating-point type ‘gdouble’ {aka ‘double’} [-Wabsolute-value]
585 |  if (abs (performance_ratio) <= G_MINDOUBLE)
|      ^~~
floaters.c: In function ‘screen_saver_floater_do_draw’:
floaters.c:735:44: warning: using integer absolute value function ‘abs’ when argument is of floating-point type ‘gdouble’ {aka ‘double’} [-Wabsolute-value]
735 |  if …
```
=> floaters: use fabs instead of abs for doubles

src/gs-window-x11.c
```
gs-window-x11.c: In function ‘gs_window_move_resize_window’:
gs-window-x11.c:379:13: warning: variable ‘widget’ set but not used [-Wunused-but-set-variable]
379 |  GtkWidget *widget;
|             ^~~~~~
```
=> gs-window-x11: Remove warning "variable ‘widget’ set but not used"

src/mate-screensaver-preferences.c
```
mate-screensaver-preferences.c:286:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
286 | config_get_lock_disabled ()
| ^~~~~~~~~~~~~~~~~~~~~~~~
```
=> Remove warning function declaration isn’t a prototype

src/gs-lock-plug.c
`dialog_timed_out` and `response_cancel_idle_cb` are [GSourceFunc](https://developer.gnome.org/glib/stable/glib-The-Main-Event-Loop.html#GSourceFunc) functions which are not called outside `g_timeout_add`; for that reason, they don't need a function casting like `date_time_update`, which is called within `g_timeout_add` and directly `date_time_update (plug);`
=> gs-lock-plug: remove function casting

savers/floaters.c, src/mate-screensaver-dialog.c, src/mate-screensaver-preferences.c
```
mate-screensaver-preferences.c:195:36: warning: declaration of 'theme_manager' shadows a global declaration [-Wshadow]
195 | get_all_theme_ids (GSThemeManager *theme_manager)
|                    ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
--
mate-screensaver-preferences.c:300:28: warning: declaration of 'job' shadows a global declaration [-Wshadow]
300 | job_set_theme (GSJob      *job,
|                ~~~~~~~~~~~~^~~
--
mate-screensaver-dialog.c:432:76: warning: declaration of 'verbose' shadows a global declaration [-Wshadow]
432 | static gboolean privileged_initialization(int* argc, char** argv, gboolean verbose)
|                                                                   ~~~~~~~~~^~~~~~~
--
mate-screensaver-dialog.c:474:93: warning: declaration of 'verbose' shadows a global declaration …
```
=> Remove warning -Wshadow

data/org.mate.screensaver.gschema.xml.in, src/gs-lock-plug.c
This change allows modification of default time and date format defined by current locale.
Closes https://github.com/mate-desktop/mate-screensaver/issues/100
Default ('local') settings maintains old behavior.
User is able to use any format defined by https://developer.gnome.org/glib/stable/glib-GDateTime.html#g-date-time-format.
Examples:
%R for time means 24H format.
%F for date means YYYY-MM-DD (ISO 8601 format).
=> Allow change of time and date formats on lock screen.

src/gs-theme-manager.c
closes #263
```C
/**
* MateMenuTree:changed:
*
* This signal is emitted when applications are added, removed, or
* upgraded.  But note the new data will only be visible after
* matemenu_tree_load_sync() or a variant thereof is invoked.
*/
matemenu_tree_signals[CHANGED] =
g_signal_new ("changed",
G_TYPE_FROM_CLASS (klass),
G_SIGNAL_RUN_LAST,
0,
NULL, NULL,
g_cclosure_marshal_VOID__VOID,
G_TYPE_NONE, 0);
```
=> gs-theme-manager: reload on menu_tree changed

savers/floaters.c, savers/slideshow.c, src/mate-screensaver-command.c, src/mate-screensaver-dialog.c, src/mate-screensaver.c
```
mate-screensaver.c:59:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
mate-screensaver-command.c:111:9: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
--
mate-screensaver-dialog.c:65:7: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
floaters.c:1152:8: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{NULL}
^
--
slideshow.c:70:10: warning: missing field 'short_name' initializer [-Wmissing-field-initializers]
{ NULL }
^
```
=> Fix build warnings about missing field initializer

src/mate-screensaver-preferences.c
```
Direct leak of 72 byte(s) in 6 object(s) allocated from:
#0 0x7f1b67c5793f in __interceptor_malloc (/lib64/libasan.so.6+0xae93f)
#1 0x7f1b666c84df in g_malloc ../glib/gmem.c:106
#2 0x7f1b666c8822 in g_malloc_n ../glib/gmem.c:344
#3 0x7f1b666eae35 in g_strdup ../glib/gstrfuncs.c:361
#4 0x7f1b6680a016 in value_lcopy_string ../gobject/gvaluetypes.c:313
#5 0x7f1b673228fc in gtk_tree_model_get_valist ../gtk/gtktreemodel.c:1812
#6 0x7f1b6732234b in gtk_tree_model_get ../gtk/gtktreemodel.c:1774
#7 0x408f82 in separator_func /home/robert/builddir.gcc/mate-screensaver/src/mate-screensaver-preferences.c:669
#8 0x7f1b6734c374 in row_is_separator ../gtk/gtktreeview.c:3113
#9 0x7f1b6735cfee in gtk_tree_view_bin_draw ../gtk/gtktreeview.c:5177
#10 0x7f1b6735c998 in draw_bin ../gtk/gtktreeview.c:5638 …
```
=> mate-screensaver-preferences: fix memory leak

savers/xdg-user-dir-lookup.c, src/gs-lock-plug.c, src/gs-watcher-x11.c, src/gs-window-x11.c
```
CFLAGS="-Wconversion -Wunused-macros -Wunused-parameter" CC=clang ./autogen.sh --prefix=/usr --enable-debug --enable-compile-warnings=maximum && make &> make.log
```
```
gs-lock-plug.c:1733:12: warning: implicit conversion loses integer precision: 'glong' (aka 'long') to 'int' [-Wshorten-64-to-32]
gs-watcher-x11.c:94:52: warning: implicit conversion loses integer precision: 'glong' (aka 'long') to 'guint' (aka 'unsigned int') [-Wshorten-64-to-32]
gs-window-x11.c:620:51: warning: implicit conversion loses integer precision: 'glong' (aka 'long') to 'guint' (aka 'unsigned int') [-Wshorten-64-to-32]
xdg-user-dir-lookup.c:74:9: warning: implicit conversion loses integer precision: 'unsigned long' to 'int' [-Wshorten-64-to-32]
```
=> Fix some -Wshorten-64-to-32 warnings

savers/floaters.c, src/gs-fade.c, src/gs-grab-x11.c, src/gs-listener-dbus.c, src/gs-manager.c, src/gs-prefs.c, src/gs-watcher-x11.c, src/gs-window-x11.c
```
gs-listener-dbus.c:366:31: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
listener->priv->throttled = throttled;
~ ^~~~~~~~~
gs-listener-dbus.c:393:33: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
listener->priv->session_idle = idle;
~ ^~~~
gs-listener-dbus.c:411:27: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
listener->priv->active = active;
~ ^~~~~~
gs-listener-dbus.c:499:33: warning: implicit conversion changes signedness: 'gboolean' (aka 'int') to 'guint' (aka 'unsigned int') [-Wsign-conversion]
listener->priv->session_idle = idle;
~ ^~~~ …
```
=> Sign conversion bool to guint

data/mate-screensaver-preferences.ui
Allows one to use <kbd>Alt+b</kbd> to reach the background selection widget, similar to other ones in the dialog.
=> mate-screensaver-preferences: Add mnemonic for background-picture

data/mate-screensaver-preferences.ui
* removes spurious leading dashes in UI file
* use a grid with variable column widths instead of 4 columns with manual ¼/¾
* align labels to the left
* add mnemonic and tooltip to the lock-delay label
=> Cleanups following #293

src/mate-screensaver-preferences.c
The scale controls the delay after which to lock the screen once the screensaver activated, not whether or not it happens -- which has its own checkbox.  So remove the "Never" wording for value 0, which was inherited from an earlier version of the activate-delay scale that is not used anymore (the activate-delay scale is now 1-120, never 0).
=> mate-screensaver-preferences: Fix lock-delay time wording
